M48
; DRILL file {KiCad 8.0.5} date 2024-12-04T18:38:02+0100
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-12-04T18:38:02+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.5
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.700
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C4.000
%
G90
G05
T1
X82.42Y-142.5
X92.58Y-142.5
T2
X87.5Y-142.5
M30
